export enum StateNameAbbreviation {
    Alabama = "Ala.",
    Alaska = "Alaska",
    Arizona = "Ariz.",
    Arkansas = "Ark.",
    California = "Calif.",
    Colorado = "Colo.",
    Connecticut = "Conn.",
    Delaware = "Del.",
    DistrictOfColumbia = "D.C.",
    Florida = "Fla.",
    Georgia = "Ga.",
    Hawaii = "Hawaii",
    Idaho = "Idaho",
    Illinois = "Ill.",
    Indiana = "Ind.",
    Iowa = "Iowa",
    Kansas = "Kans.",
    Kentucky = "Ky.",
    Louisiana = "La.",
    Maine = "Maine",
    Maryland = "Md.",
    Massachusetts = "Mass.",
    Michigan = "Mich.",
    Minnesota = "Minn.",
    Mississippi = "Miss.",
    Missouri = "Mo.",
    Montana = "Mont.",
    Nebraska = "Nebr.",
    Nevada = "Nev.",
    NewHampshire = "N.H.",
    NewJersey = "N.J.",
    NewMexico = "N.M.",
    NewYork = "N.Y.",
    NorthCarolina = "N.C.",
    NorthDakota = "N.D.",
    Ohio = "Ohio",
    Oklahoma = "Okla.",
    Oregon = "Ore.",
    Pennsylvania = "Pa.",
    RhodeIsland = "R.I.",
    SouthCarolina = "S.C.",
    SouthDakota = "S.D.",
    Tennessee = "Tenn.",
    Texas = "Tex.",
    Utah = "Utah",
    Vermont = "Vt.",
    Virginia = "Va.",
    Washington = "Wash.",
    WestVirginia = "W.Va.",
    Wisconsin = "Wis.",
    Wyoming = "Wyo."
}

export const isStateNameAbbreviation = (value: string): value is StateNameAbbreviation => {
    return Object.values(StateNameAbbreviation)
        .map(el => el.toString())
        .includes(value);
}
